service: lumen-dashboard
provider:
  name: aws
  runtime: nodejs6.10
plugins:
  - serverless-offline
  - serverless-webpack
functions:
  generate:
    handler: handler.query # required, handler set in AWS Lambda
    events:
      - http:
          path: query
          method: get

