const FETCH_STIM_BEGIN = 'FETCH_STIM_BEGIN';
const FETCH_STIM_SUCCESS = 'FETCH_STIM_SUCCESS';
const FETCH_STUDIES_OVERVIEW_SUCCESS = 'FETCH_STUDIES_OVERVIEW_SUCCESS';
const FETCH_STIM_ERROR = 'FETCH_STIM_ERROR';
const ADD_COMPARE_STUDY = 'ADD_COMPARE_STUDY';
const REMOVE_COMPARE_STUDY = 'REMOVE_COMPARE_STUDY';
const CLEAR_CHECKED_STUDIES = 'CLEAR_CHECKED_STUDIES';
const CHECK_ALL_IN_STEP = 'CHECK_ALL_IN_STEP';
const REMOVE_ALL_IN_STEP = 'REMOVE_ALL_IN_STEP';
const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';



export default {
  FETCH_STIM_BEGIN,
  FETCH_STIM_ERROR,
  FETCH_STIM_SUCCESS,
  FETCH_STUDIES_OVERVIEW_SUCCESS,
  ADD_COMPARE_STUDY,
  REMOVE_COMPARE_STUDY,
  CLEAR_CHECKED_STUDIES,
  CHECK_ALL_IN_STEP,
  REMOVE_ALL_IN_STEP,
  AUTHENTICATION_ERROR
};
