const FETCH_TOTAL_INFO_BEGIN = 'FETCH_TOTAL_INFO_BEGIN';
const FETCH_TOTAL_INFO_SUCCESS = 'FETCH_TOTAL_INFO_SUCCESS';
const FETCH_TOTAL_INFO_ERROR = 'FETCH_TOTAL_INFO_ERROR';

export default {
    FETCH_TOTAL_INFO_BEGIN,
    FETCH_TOTAL_INFO_SUCCESS,
    FETCH_TOTAL_INFO_ERROR
};
